# Generated by Django 4.0.4 on 2023-01-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SteamDB',
            fields=[
                ('appid', models.TextField(primary_key=True, serialize=False)),
                ('json_path', models.TextField()),
            ],
        ),
    ]
